Test.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -18,17 +18,19 @@ jobs:
       run: |
         docker build -t metacall/nodejs-c-liburing-example .
         docker run --rm -p 8000:8000 --name metacall_test -d metacall/nodejs-c-liburing-example
-        RETRIES=0
-        while true; do
-            wget --server-response -q "http://localhost:8000" || true
-            HTTP_CODE="$(wget --server-response -q "http://localhost:8000" 2>&1 | grep "HTTP/" | awk '{print $2}')"
-            if [[ "$HTTP_CODE" -eq "200" ]]; then
-                echo "Service is ready (HTTP 200)."
-                exit 0
-            elif [[ "$RETRIES" -ge "20" ]]; then
-                echo "Max retries reached. Service not ready."
-                exit 1
-            fi
-            RETRIES=$((RETRIES + 1))
-            sleep 5
-        done
+        wget --retries=20 --server-response "http://localhost:8000"
+
+# RETRIES=0
+# while true; do
+#     wget --server-response -q "http://localhost:8000" || true
+#     HTTP_CODE="$(wget --server-response -q "http://localhost:8000" 2>&1 | grep "HTTP/" | awk '{print $2}')"
+#     if [[ "$HTTP_CODE" -eq "200" ]]; then
+#         echo "Service is ready (HTTP 200)."
+#         exit 0
+#     elif [[ "$RETRIES" -ge "20" ]]; then
+#         echo "Max retries reached. Service not ready."
+#         exit 1
+#     fi
+#     RETRIES=$((RETRIES + 1))
+#     sleep 5
+# done
